use engine::{BitDepth, DigitalMeter, Matrix, SampleRate};

use crate::{
    Connector, DeviceConfig, ParamKind, PortKind,
    catalog::{
        BITS, CatalogEntry, FormFactor, GridAxis, GridSpec, HOST_RATE_HZ, InternalEdge, PortUi,
        ReadoutSpec, ReadoutUi,
    },
};

const USB_SENDS: &str = "usb_sends";
const USB_RETURNS: &str = "usb_returns";
// Configs are floats
const DEFAULT_USB_CHANNELS_CONFIG: f32 = 2.0;

fn usb_channel_count(cfg: &DeviceConfig) -> (usize, usize) {
    let sends = cfg
        .get_or(USB_SENDS, DEFAULT_USB_CHANNELS_CONFIG)
        .round()
        .max(1.0) as usize;

    let returns = cfg
        .get_or(USB_RETURNS, DEFAULT_USB_CHANNELS_CONFIG)
        .round()
        .max(1.0) as usize;

    (sends, returns)
}

/// Diagonal loopback crosspoint defaults for an `n_in`→`m_out` matrix: send k → return k at unity for
/// k < min(n_in, m_out), silent elsewhere (row-major `i·m_out + j`). Every return carries signal out
/// of the box — the 8i6 matrix's identity-default philosophy.
fn loopback_defaults(n_in: usize, m_out: usize) -> Vec<f32> {
    let mut d = vec![0.0; n_in * m_out];
    for k in 0..n_in.min(m_out) {
        d[k * m_out + k] = 1.0;
    }
    d
}

// The `computer` — the 8i6's USB peer, without which a multichannel USB port has no legal partner
// and the 8i6 can't be played end-to-end. A real computer has no channel count of its own; it adapts
// to whatever the attached interface's driver publishes. So its shape is **config-driven**: hidden
// `usb_sends` / `usb_returns` keys (written by web-side enumeration on USB connect) size an
// **N-lane input** (the "USB sends" the interface records into the DAW) and an **M-lane output** (the
// "USB returns" the DAW plays back). Unattached, it defaults to **2×2** — the built-in sound card.
//
// It's a **two-node, lane-bundled chassis** regardless of counts:
//   * node 0 — a `DigitalMeter(N)` metering every send lane (Peak/RMS readouts, the DAW's input
//     meters), all N lanes behind one port;
//   * node 1 — an N→M routing `Matrix` (lane-bundled single ports) whose default is the **diagonal
//     loopback** (send k → return k over `min(N, M)`), so the classic playable loop closes out of
//     the box: mic/synth → preamp → AD → USB → computer → USB return → DA → monitor.
// One internal edge (the N-lane metered bus) joins them. The `Matrix` (not a fixed mux) cleanly
// absorbs the N≠M asymmetry with **no dangling ports** and makes the loopback runtime-routable (the
// seam a real DAW-mixer focus surface will drive later). A real DAW is far more than this; the
// "correct-enough, never false" line keeps the signal path and levels honest and leaves the
// application layer out of scope.
pub(super) const COMPUTER: CatalogEntry = CatalogEntry {
    type_id: "computer",
    name: "Computer",
    // A compact laptop-ish DAW host, trimmed to sit with the 8i6; tall enough to show the USB send
    // meters on the front. A true 15" footprint is a later realistic variant.
    form_factor: FormFactor::Desktop {
        width_mm: 240.0,
        height_mm: 28.0,
        depth_mm: 175.0,
    },
    nodes: &[
        |cfg| {
            let (sends, _returns) = usb_channel_count(cfg);
            Box::new(DigitalMeter::new(
                SampleRate::new(HOST_RATE_HZ),
                BitDepth::new(BITS),
                sends as u16,
            ))
        },
        |cfg| {
            let (sends, returns) = usb_channel_count(cfg);
            Box::new(Matrix::new_single_ports(
                SampleRate::new(HOST_RATE_HZ),
                BitDepth::new(BITS),
                sends,
                returns,
                loopback_defaults(sends, returns),
            ))
        },
    ],
    internal: &[InternalEdge {
        // DigitalMeter -> Matrix
        from_node: 0,
        from_port: 0,
        to_node: 1,
        to_port: 0,
    }],
    // All exposed params are the matrix's N·M crosspoints (the meter has none), generated by the grid.
    params: &[],
    // The N→M routing matrix (node 1, the only param-contributing node). Sends (rows) × returns
    // (cols); axis names generated from the face's counts, driven at runtime, loopback by default.
    param_grid: Some(GridSpec {
        inputs: GridAxis::Generated { prefix: "Send" },
        outputs: GridAxis::Generated { prefix: "Return" },
        kind: ParamKind::Knob,
        unit: "×",
    }),
    param_groups: &[],
    inputs: &[PortUi {
        label: "USB In",
        kind: PortKind::Digital,
        connector: Connector::Usb,
    }],
    outputs: &[PortUi {
        label: "USB Out",
        kind: PortKind::Digital,
        connector: Connector::Usb,
    }],
    // The USB return (output 0) is the DAW's playback — one block behind what it records — so edges
    // from it are **delayed**: `build_patch` wires them with round-trip latency, letting the
    // interface → computer → interface monitoring loop close without a same-block cycle.
    delayed_outputs: &[0],
    // The single USB-C jack is duplex: USB Out (0) + USB In (0) are one physical connector.
    duplex_links: &[(0, 0)],
    // Per-lane send meters, in node order: each meter contributes (Peak, RMS) in decl order.
    readouts: ReadoutSpec::PerLane {
        lane_prefix: "Send",
        per: &[
            ReadoutUi {
                label: "Peak",
                unit: "dBFS",
            },
            ReadoutUi {
                label: "RMS",
                unit: "dBFS",
            },
        ],
    },
    configs: &[],
};

#[cfg(test)]
mod tests {
    use engine::Graph;

    use super::loopback_defaults;
    use crate::scene::ConfigSetting;
    use crate::{DeviceConfig, PortDirection, descriptors, instantiate};

    /// The loopback default routes send k → return k on the diagonal, but only over `min(sends,
    /// returns)` lanes — every return carries a signal, no send is left dangling a default.
    #[test]
    fn loopback_defaults_are_the_min_diagonal() {
        // 2×2 (the built-in card), row-major id = i·m_out + j: (0,0)=id 0 and (1,1)=id 1·2+1=3 at
        // unity; the off-diagonal muted.
        assert_eq!(loopback_defaults(2, 2), vec![1.0, 0.0, 0.0, 1.0]);

        // Rectangular 3→2: the diagonal runs only to min(3,2)=2 — send 0→ret 0, send 1→ret 1; send 2
        // has no matching return, so its whole row (ids 4,5) stays muted.
        assert_eq!(loopback_defaults(3, 2), vec![1.0, 0.0, 0.0, 1.0, 0.0, 0.0]);
    }

    /// Unattached, the `computer` is the **built-in 2×2 sound card**: a two-node chassis — meter-bank(2)
    /// → lane-matrix(2→2) — wired by one lane-bundled internal edge. USB in exposes the meter bank, USB
    /// out the matrix; 4 crosspoints and 4 (Peak, RMS) readouts, no dangling ports.
    #[test]
    fn default_computer_is_the_2x2_built_in_card() {
        let mut g = Graph::new();
        let dev = instantiate("computer", &DeviceConfig::EMPTY, &mut g)
            .expect("computer is in the catalog");

        assert_eq!(dev.nodes.len(), 2, "meter-bank + matrix");
        assert_eq!(g.connection_count(), 1, "one lane-bundled internal edge");

        assert_eq!(dev.inputs, vec![(dev.nodes[0], 0)], "USB in = meter bank");
        assert_eq!(dev.outputs, vec![(dev.nodes[1], 0)], "USB out = matrix");

        // 2×2 matrix → 4 crosspoints, all on the matrix (node 1).
        assert_eq!(dev.params.len(), 4, "2×2 crosspoints");
        assert!(
            dev.params
                .iter()
                .all(|t| t.len() == 1 && t[0].0 == dev.nodes[1]),
            "every exposed param is a matrix crosspoint"
        );

        // 2 send lanes × (Peak, RMS) → 4 readouts, all on the meter bank (node 0).
        assert_eq!(dev.readouts.len(), 4, "2 lanes × (peak, rms)");
        assert!(
            dev.readouts.iter().all(|r| r.0 == dev.nodes[0]),
            "every readout is on the meter bank"
        );
    }

    /// The type-catalog descriptor (built with the EMPTY config) advertises the default 2×2 face: USB
    /// ports carry 2 lanes each, labels are **generated** from the counts, and the matrix defaults to
    /// the diagonal loopback.
    #[test]
    fn default_computer_descriptor_is_2x2_with_generated_labels() {
        let dev = descriptors()
            .into_iter()
            .find(|d| d.type_id == "computer")
            .expect("computer is in the catalog");

        let usb_in = dev
            .ports
            .iter()
            .find(|p| p.direction == PortDirection::Input)
            .expect("a USB input");
        let usb_out = dev
            .ports
            .iter()
            .find(|p| p.direction == PortDirection::Output)
            .expect("a USB output");
        assert_eq!(usb_in.channels, 2, "USB in = 2 send lanes");
        assert_eq!(usb_out.channels, 2, "USB out = 2 return lanes");

        // 2×2 → 4 crosspoints, labels synthesized "Send i → Return j" row-major.
        assert_eq!(dev.params.len(), 4);
        assert_eq!(dev.params[0].label, "Send 1 → Return 1");
        assert_eq!(dev.params[3].label, "Send 2 → Return 2");

        // 2 lanes × (Peak, RMS) → 4 readouts, labels synthesized "Send k Peak/RMS", lane-then-measure.
        assert_eq!(dev.readouts.len(), 4);
        assert_eq!(dev.readouts[0].label, "Send 1 Peak");
        assert_eq!(dev.readouts[1].label, "Send 1 RMS");
        assert_eq!(dev.readouts[2].label, "Send 2 Peak");

        // Diagonal loopback default: (send 1,ret 1)=id 0 and (send 2,ret 2)=id 1·2+1=3 at unity.
        for (id, p) in dev.params.iter().enumerate() {
            let expected = if id == 0 || id == 3 { 1.0 } else { 0.0 };
            assert_eq!(p.default, expected, "crosspoint {id} default");
        }
    }

    /// Attaching an interface writes its published shape as hidden `usb_sends`/`usb_returns` config; the
    /// computer re-sizes to it — same two-node chassis, now 8-lane meter → 8×6 matrix.
    #[test]
    fn configured_computer_expands_to_8x6() {
        let settings = [
            ConfigSetting {
                key: "usb_sends".into(),
                value: 8.0,
            },
            ConfigSetting {
                key: "usb_returns".into(),
                value: 6.0,
            },
        ];
        let config = DeviceConfig::new(&settings);
        let mut g = Graph::new();
        let dev = instantiate("computer", &config, &mut g).expect("computer is in the catalog");

        assert_eq!(dev.nodes.len(), 2, "still meter-bank + matrix");
        assert_eq!(dev.params.len(), 48, "8×6 crosspoints");
        assert_eq!(dev.readouts.len(), 16, "8 send lanes × (peak, rms)");
    }
}
